settings:
  parallel: true

driver:
  name: dokken
  chef_version: 12.5.1

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

platforms:
- name: centos-5
  driver:
    image: centos:5

- name: centos-6
  driver:
    image: centos:6

- name: centos-7
  driver:
    image: centos:7

suites:
- name: connectors
  run_list:
  - recipe[yum-mysql-community::connectors]
  attributes: {}

- name: mysql56
  run_list:
  - recipe[yum-mysql-community::mysql56]
  attributes: {}

- name: mysql57
  run_list:
  - recipe[yum-mysql-community::mysql57]
  attributes: {}
